#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: Curriculum vitae
url: 'https://fgaens.github.io/curriculum-vitae/'

#baseurl: '/curriculum-vitae'

description: A beautiful Jekyll theme for creating a curriculum vitae
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: green # blue turquoise green berry orange ceramic
chrome_mobile_color: #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar

# Google Analytics
google-analytics: G-58G9FSVMMB

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
compress-site: yes

encoding: "UTF-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false
